export let folders = [
	{
		level: 5,
		path: `Admission_Record`,
		title: `Admission Record`,
		name: `admissionrecord3`,
		url: `https://github.com/Sandeep-morya/Admission_Record/archive/refs/heads/main.zip`,
	},
	{
		level: 6,
		path: `Calculator`,
		title: `Calculator`,
		name: `calculator4`,
		url: `https://github.com/Sandeep-morya/Calculator/archive/refs/heads/main.zip`,
	},
	{
		level: 4,
		path: `CSS_Projects`,
		title: `CSS Projects`,
		name: `cssproject3`,
		url: `https://github.com/Sandeep-morya/CSS_Projects/archive/refs/heads/main.zip`,
	},
	{
		level: 3,
		path: `E-Commerce`,
		title: `E Commerce Site-1st`,
		name: `ecommerce2`,
		url: `https://github.com/Sandeep-morya/E-Commerce/archive/refs/heads/main.zip`,
	},
	{
		level: 2,
		path: `First_Website`,
		title: `First Website`,
		name: `firstwebsite2`,
		url: `https://github.com/Sandeep-morya/First_Website/archive/refs/heads/main.zip`,
	},
	{
		level: 8,
		path: `JavaScript_practice_assignments/STUDENT-MANAGEMENT-SYSTEM`,
		title: `Students Mangement`,
		name: `studentmanagementsystem3`,
		url: `https://github.com/Sandeep-morya/JavaScript_practice_assignments/archive/refs/heads/main.zip`,
	},
	{
		level: 1,
		path: `JavaScript_practice_assignments/Let_dice_decide`,
		title: `Let Dice Decide`,
		name: `letdicedecide1`,
		url: `https://github.com/Sandeep-morya/JavaScript_practice_assignments/archive/refs/heads/main.zip`,
	},
	{
		level: 7,
		path: `Movie_Booking`,
		title: `Movie Booking`,
		name: `moviebooking3`,
		url: `https://github.com/Sandeep-morya/Movie_Booking/archive/refs/heads/main.zip`,
	},
	{
		level: 9,
		path: `/SparkAmerica_Clone/Index.html`,
		title: `SparkAmerica Clone`,
		name: `spartkamericaclone4`,
		url: `https://github.com/Sandeep-morya/SparkAmerica_Clone/archive/refs/heads/main.zip`,
	},
	{
		level: 10,
		path: `/music-player-1.0/Index.html`,
		title: `Music Player`,
		name: `musicplayer`,
		url: `https://github.com/Sandeep-morya/music-player-1.0/archive/refs/heads/main.zip`,
	},
	{
		level: 10,
		path: `Disney_plus-Hotstar_clone`,
		title: `Disney+ Clone`,
		name: `disney+plushotstar5`,
		url: `https://github.com/Sandeep-morya/Desney_plus-Hotstar_clone/archive/refs/heads/main.zip`,
	},
	{
		level: 11,
		path: `Youtube_clone`,
		title: `YouTube Clone`,
		name: `youtubeclone5`,
		url: `https://github.com/Sandeep-morya/Youtube_clone/archive/refs/heads/main.zip`,
	},
	{
		level: 12,
		path: `Giphy_clone`,
		title: `Giphy Clone`,
		name: `giphy_cloneclone5`,
		url: `https://github.com/Sandeep-morya/Giphy_clone/archive/refs/heads/main.zip`,
	},
	{
		level: 13,
		path: `https://testing-movie-app.vercel.app/`,
		title: `MoviesLand`,
		name: `moviesland`,
		url: `https://github.com/Sandeep-morya/Automation/archive/refs/heads/master.zip`,
	},
	{
		level: 14,
		path: `https://todo-with-type-script.vercel.app/`,
		title: `Todo App`,
		name: `todotypescript`,
		url: `https://github.com/Sandeep-morya/ga-todo-app/archive/refs/heads/main.zip`,
	},
	{
		level: 15,
		path: `https://merch-clone-onm8ai5e2-sandeep-morya.vercel.app//`,
		title: `Merch clone`,
		name: `todotypescript`,
		url: `https://github.com/Sandeep-morya/Merch-clone/archive/refs/heads/master.zip`,
	},

	{
		level: 16,
		path: `https://railman.netlify.app/`,
		title: `Railman`,
		name: `railmanRailman`,
		url: `https://github.com/Sandeep-morya/Automation/archive/refs/heads/master.zip`,
	},
	{
		level: 17,
		path: `https://netflix-clone-three-pi.vercel.app/`,
		title: `netflix Clone`,
		name: `netflixclone`,
		url: `https://github.com/Sandeep-morya/Netflix_Clone/archive/refs/heads/main.zip`,
	},
	{
		level: 18,
		path: `https://www.npmjs.com/package/colorprint-js`,
		title: `NPM colorprint`,
		name: `npmcolorprint`,
		url: `https://github.com/Sandeep-morya/ColorPrint/archive/refs/heads/master.zip`,
	},
	{
		level: 19,
		path: `https://auth-api-6b8l.onrender.com`,
		title: `Auth API`,
		name: `authapi`,
		url: `https://github.com/Sandeep-morya/Authentication-API/archive/refs/heads/main.zip`,
	},
	{
		level: 20,
		path: `https://sandeep-auraly.vercel.app/`,
		title: `Auraly`,
		name: `auralymusicvideo`,
		url: `https://github.com/Sandeep-morya/Auraly/archive/refs/heads/main.zip`,
	},
	{
		level: 21,
		path: `https://cloudynest.vercel.app/`,
		title: `CloudyNest`,
		name: `cloudynestonlineshopping`,
		url: `https://github.com/Sandeep-morya/CloudyNest/archive/refs/heads/main.zip`,
	},
	{
		level: 22,
		path: `https://advance-facebook-clone.vercel.app/login`,
		title: `Facebook clone`,
		name: `auraly`,
		url: `https://github.com/Sandeep-morya/Facebook_clone/archive/refs/heads/main.zip`,
	},
];
